eureka:
  client:
    service-url:
      DefaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dudj/config-repo.git
          username: 13020078873@163.com
          password: LKK521liukeke
          basedir: D:\javaproject\self\sc0915\config\basedir
  rabbitmq:
    host: 47.93.202.38
    username: guest
    password: guest
    port: 5672
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
