eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dudj/config-repo.git
          username: 13020078873@163.com
          password: LKK521liukeke
          basedir: D:\ddj\sc0915\config\basedir